"""Arm models Kintrace can diagnose.

Each arm is a joint count, joint names and a batched forward kinematics
function that returns the flange pose in the robot base frame. The rest of
Kintrace only talks to an Arm, so adding a robot means adding one here.

Which arm a log uses comes from its config: config["arm"] ("ur5e" or
"so101"). Old logs have no "arm" key and are UR5e-class.

  ur5e   UR5e-class 6-joint arm, standard DH (see robot.py). The simulated cell.
  so101  LeRobot SO-101 follower, 5 arm joints (the gripper joint is not part
         of the chain; the tool is clipped to the fixed jaw).
  panda  Franka Emika Panda / FR3, 7 joints. The arm every DROID episode was
         recorded on (see kintrace/droid). Modified DH from Franka's
         published kinematics; flange is the panda_link8 frame.

SO-101 source: joint origins and axes copied from so101_new_calib.urdf in
github.com/TheRobotStudio/SO-ARM100, file Simulation/SO101/so101_new_calib.urdf
(main branch, downloaded 2026-09-26; generated by onshape-to-robot). The
"new_calib" URDF is the one meant to match LeRobot's current calibration,
where 0 deg is the middle of each joint's recorded range. Whether that zero
and each joint's sign match a real LeRobot arm has NOT been checked on
hardware. `kintrace rig commission` fits the remaining zero offsets and can
search joint signs, so small mismatches get absorbed there.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
from scipy.spatial.transform import Rotation

from . import robot


@dataclass(frozen=True)
class Arm:
    name: str
    joint_names: tuple
    fk_fn: Callable
    home_q: np.ndarray
    # a few points in the work area, used to say how far a camera shift
    # moves things the camera looks at ("parts appear N mm off")
    work_pts: np.ndarray

    @property
    def n(self) -> int:
        return len(self.joint_names)

    def fk(self, q: np.ndarray) -> np.ndarray:
        return self.fk_fn(q)


# --------------------------------------------------------------------------
# UR5e-class (unchanged, uses robot.py)
# --------------------------------------------------------------------------
UR5E = Arm(
    name="ur5e",
    joint_names=tuple(robot.JOINT_NAMES),
    fk_fn=robot.fk,
    home_q=robot.HOME_Q.copy(),
    work_pts=np.array([[0.47, 0.0, 0.04], [0.35, -0.45, 0.04], [0.6, 0.15, 0.04]]),
)


# --------------------------------------------------------------------------
# SO-101 follower, from the URDF (see module docstring for the source)
# --------------------------------------------------------------------------
# (joint, parent -> child, origin xyz, origin rpy); every joint turns about its local z
SO101_JOINTS = [
    ("shoulder_pan", [0.0388353, -8.97657e-09, 0.0624], [3.14159, 4.18253e-17, -3.14159]),
    ("shoulder_lift", [-0.0303992, -0.0182778, -0.0542], [-1.5708, -1.5708, 0.0]),
    ("elbow_flex", [-0.11257, -0.028, 1.73763e-16], [-3.63608e-16, 8.74301e-16, 1.5708]),
    ("wrist_flex", [-0.1349, 0.0052, 3.62355e-17], [4.02456e-15, 8.67362e-16, -1.5708]),
    ("wrist_roll", [5.55112e-17, -0.0611, 0.0181], [1.5708, 0.0486795, 3.14159]),
]
# URDF joint limits (rad)
SO101_LIMITS = np.array([
    [-1.91986, 1.91986],
    [-1.74533, 1.74533],
    [-1.69, 1.69],
    [-1.65806, 1.65806],
    [-2.74385, 2.84121],
])
# gripper_frame_joint: the jaw tip frame, fixed to gripper_link (the flange here)
SO101_GRIPPER_FRAME_XYZ = np.array([-0.0079, -0.000218121, -0.0981274])
SO101_GRIPPER_FRAME_RPY = np.array([0.0, 3.14159, 0.0])


def _origin(xyz, rpy) -> np.ndarray:
    T = np.eye(4)
    # URDF rpy: fixed-axis roll, pitch, yaw -> R = Rz(yaw) Ry(pitch) Rx(roll)
    T[:3, :3] = Rotation.from_euler("xyz", rpy).as_matrix()
    T[:3, 3] = xyz
    return T


_SO101_ORIGINS = np.stack([_origin(x, r) for _, x, r in SO101_JOINTS])


def so101_fk(q: np.ndarray) -> np.ndarray:
    """gripper_link pose(s) in the SO-101 base_link frame.

    q: (5,) or (N, 5) joint angles in radians, URDF convention.
    Returns (4, 4) or (N, 4, 4).
    """
    q = np.asarray(q, dtype=float)
    single = q.ndim == 1
    q = np.atleast_2d(q)
    n = q.shape[0]
    T = np.tile(np.eye(4), (n, 1, 1))
    for i in range(len(SO101_JOINTS)):
        c, s = np.cos(q[:, i]), np.sin(q[:, i])
        Rz = np.tile(np.eye(4), (n, 1, 1))
        Rz[:, 0, 0], Rz[:, 0, 1], Rz[:, 1, 0], Rz[:, 1, 1] = c, -s, s, c
        T = T @ _SO101_ORIGINS[i] @ Rz
    return T[0] if single else T


SO101 = Arm(
    name="so101",
    joint_names=("shoulder pan", "shoulder lift", "elbow flex", "wrist flex", "wrist roll"),
    fk_fn=so101_fk,
    home_q=np.zeros(5),
    work_pts=np.array([[0.20, 0.0, 0.0], [0.15, -0.10, 0.0], [0.15, 0.10, 0.0]]),
)

# --------------------------------------------------------------------------
# Franka Panda / FR3, modified (Craig) DH from Franka's control interface docs
# --------------------------------------------------------------------------
PANDA_A = np.array([0.0, 0.0, 0.0, 0.0825, -0.0825, 0.0, 0.088, 0.0])
PANDA_D = np.array([0.333, 0.0, 0.316, 0.0, 0.384, 0.0, 0.0, 0.107])
PANDA_ALPHA = np.array([0.0, -np.pi / 2, np.pi / 2, np.pi / 2, -np.pi / 2, np.pi / 2, np.pi / 2, 0.0])
PANDA_HOME_Q = np.array([0.0, -np.pi / 4, 0.0, -3 * np.pi / 4, 0.0, np.pi / 2, np.pi / 4])
# panda_link8 -> fingertip centre of the stock Franka Hand with fingers closed
PANDA_HAND_TIP = np.array([0.0, 0.0, 0.1034])


def panda_fk(q: np.ndarray) -> np.ndarray:
    """Flange (panda_link8) pose(s) in the panda_link0 frame.

    q: (7,) or (N, 7) joint angles in radians. Returns (4, 4) or (N, 4, 4).
    Modified DH: T_i = Rx(alpha_i) Tx(a_i) Rz(theta_i) Tz(d_i), plus a fixed
    flange transform (a=0, d=0.107, theta=0).
    """
    q = np.asarray(q, dtype=float)
    single = q.ndim == 1
    q = np.atleast_2d(q)
    n = q.shape[0]
    theta = np.c_[q, np.zeros(n)]
    T = np.tile(np.eye(4), (n, 1, 1))
    for i in range(8):
        ct, st = np.cos(theta[:, i]), np.sin(theta[:, i])
        ca, sa = np.cos(PANDA_ALPHA[i]), np.sin(PANDA_ALPHA[i])
        A = np.zeros((n, 4, 4))
        A[:, 0, 0] = ct
        A[:, 0, 1] = -st
        A[:, 0, 3] = PANDA_A[i]
        A[:, 1, 0] = st * ca
        A[:, 1, 1] = ct * ca
        A[:, 1, 2] = -sa
        A[:, 1, 3] = -sa * PANDA_D[i]
        A[:, 2, 0] = st * sa
        A[:, 2, 1] = ct * sa
        A[:, 2, 2] = ca
        A[:, 2, 3] = ca * PANDA_D[i]
        A[:, 3, 3] = 1.0
        T = T @ A
    return T[0] if single else T


PANDA = Arm(
    name="panda",
    joint_names=("J1", "J2", "J3", "J4", "J5", "J6", "J7"),
    fk_fn=panda_fk,
    home_q=PANDA_HOME_Q.copy(),
    work_pts=np.array([[0.5, 0.0, 0.05], [0.4, -0.3, 0.05], [0.4, 0.3, 0.05]]),
)

ARMS = {"ur5e": UR5E, "so101": SO101, "panda": PANDA}


def get(name: str) -> Arm:
    try:
        return ARMS[name]
    except KeyError:
        raise ValueError(f"unknown arm '{name}', known: {', '.join(ARMS)}") from None


def for_config(cfg: dict | None) -> Arm:
    """The arm a log was recorded on. Logs without an 'arm' key are UR5e-class."""
    if not cfg or "arm" not in cfg:
        return UR5E
    return get(cfg["arm"])
